### ISSUE TITLE
"implicit parent-node creation behavior" is broken

### ISSUE THREAD

**Issue by j4m3s** [cmprescott/ansible-xml#81] opened 2016-10-01 19:51 UTC
[Line 132 of the Readme](https://github.com/cmprescott/ansible-xml/blame/b9ec0755560b86d3384ca6f380e96c478bbb7e03/README.md#L132) says that the you can set a node's value and parent nodes will be implicitly created.  This makes a lot of sense and avoids a mass of conditional checks to ensure parent nodes exist (and adding them if they don't).  However it looks like this functionality is broken.

Given the file:

``` xml
<user>
  <properties>
    <something/>
  </properties>
</user>
```

and the following ansible task:

``` yaml
- xml:
    file: "config.xml"
    xpath: "/user/properties/several/deep"
    value: "doink"
```

the following xml should result:

``` xml
<user>
  <properties>
    <something/>
      <several>
        <deep>doink</deep>
      </several>
  </properties>
</user>
```

However, instead, the following error is output:
`FAILED! => {"changed": false, "failed": true, "msg": "Xpath /user/properties/several/deep does not reference a node!"}`

The same applies to attributes on non-existent nodes.

**Comment by dodok1** [comment] 2016-11-29 17:05
I think this is duplicate of #37

**Comment by j4m3s** [comment] 2016-11-29 19:33
The symptoms look the same, but the other issue is marked as an enhancement.  What I've called-out here is that the module doesn't function according to the readme, which implies it's a defect.

**Closed** 2017-02-16 21:40 UTC
