### ISSUE TITLE
Spaces between elements breaks pretty_print

### ISSUE THREAD

**Issue by deyanstoykov** [cmprescott/ansible-xml#84] opened 2016-11-03 13:59 UTC
When using input_type=xml and having a space between elements, pretty_print doesn't work.
Steps to reproduce:

```
# cat /tmp/empty.xml
<?xml version='1.0' encoding='UTF-8'?>
<tag1></tag1>

# ansible localhost -m xml -a "file=/tmp/empty.xml pretty_print=true input_type=xml xpath=/tag1 add_children='<bean><Property/></bean>'"

# cat /tmp/empty.xml
<?xml version='1.0' encoding='UTF-8'?>
<tag1>
  <bean>
    <Property/>
  </bean>
</tag1>

# ansible localhost -m xml -a "file=/tmp/empty.xml pretty_print=true input_type=xml xpath=/tag1 add_children='<bean> <Property/></bean>'"

# cat /tmp/empty.xml
<?xml version='1.0' encoding='UTF-8'?>
<tag1>
  <bean>
    <Property/>
  </bean>
  <bean> <Property/></bean>
</tag1>
```

**Comment by dagwieers** [comment] 2017-08-09 11:18
The xml module is upstream now (and ships with Ansible v2.4).

**Please close this issue**, and if needed, open a new issue at: https://github.com/ansible/ansible/issues

**Comment by sm4rk0** [comment] 2017-08-10 09:49
I reproduced this issue with ansible devel and lxml 3.8.0
@deyanstoykov Would you please copy this issue over to ansible/ansible?

**Comment by sm4rk0** [comment] 2017-08-10 10:02
Just checked. The cause is within etree.tostring() from lxml and it's not a bug, but a feature:
http://lxml.de/FAQ.html#why-doesn-t-the-pretty-print-option-reformat-my-xml-output
I propose closing this issue.

**Comment by dagwieers** [comment] 2017-08-10 10:08
I would like to start listing caveats with the xml module. We can start compiling a list on the Wiki, then move the important items to the notes of the module documentation.

**Comment by sm4rk0** [comment] 2017-08-14 22:52
This behaviour is noted [here](https://github.com/ansible/community/wiki/Module:-xml), so this issue now can be closed.

**Closed by sm4rk0** 2017-08-14 22:52 UTC
