### ISSUE TITLE
Removing value results in MODULE FAILURE

### ISSUE THREAD

**Issue by wheelq** [cmprescott/ansible-xml#68] opened 2016-06-15 10:24 UTC
```yaml
- xml: file=./1.xml xpath=/testing/@location
```

results in:
```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by dagwieers** [comment] 2017-08-09 11:19
The xml module is upstream now (and ships with Ansible v2.4).

**Please close this issue**, and retest against the new upstream xml module. If needed, open a new issue at: https://github.com/ansible/ansible/issues

**Comment by dagwieers** [comment] 2017-08-24 09:54
I can confirm this problem, albeit the message has greatly improved. But we can make it even better.

Currently I get a clearer error, but too much noise. The backtrace is unneeded here.
```
[dag@moria ansible.git]$ ansible -m xml -a "file=1.xml xpath=/testing/@location" -CD localhost -v
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: lxml.etree.XPathEvalError: Invalid expression
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_XGTUn1/ansible_module_xml.py\", line 755, in <module>\n    main()\n  File \"/tmp/ansible_XGTUn1/ansible_module_xml.py\", line 750, in main\n    ensure_xpath_exists(module, doc, xpath, namespaces)\n  File \"/tmp/ansible_XGTUn1/ansible_module_xml.py\", line 486, in ensure_xpath_exists\n    changed = check_or_make_target(module, tree, xpath, namespaces)\n  File \"/tmp/ansible_XGTUn1/ansible_module_xml.py\", line 424, in check_or_make_target\n    changed = check_or_make_target(module, tree, inner_xpath, namespaces)\n  File \"/tmp/ansible_XGTUn1/ansible_module_xml.py\", line 423, in check_or_make_target\n    if not is_node(tree, inner_xpath, namespaces):\n  File \"/tmp/ansible_XGTUn1/ansible_module_xml.py\", line 267, in is_node\n    if xpath_matches(tree, xpath, namespaces):\n  File \"/tmp/ansible_XGTUn1/ansible_module_xml.py\", line 291, in xpath_matches\n    if tree.xpath(xpath, namespaces=namespaces):\n  File \"src/lxml/lxml.etree.pyx\", line 2287, in lxml.etree._ElementTree.xpath (src/lxml/lxml.etree.c:68382)\n  File \"src/lxml/xpath.pxi\", line 359, in lxml.etree.XPathDocumentEvaluator.__call__ (src/lxml/lxml.etree.c:173282)\n  File \"src/lxml/xpath.pxi\", line 227, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:171653)\nlxml.etree.XPathEvalError: Invalid expression\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

**Comment by dagwieers** [comment] 2017-08-24 10:49
Ok, so I looked into this and made a change so that now we parse and evaluate the xpath expression by default (when provided). I am not sure if this related to your problem, but without the XML file you used, I am unable to reproduce your issue. So I am closing this issue, but feel free to send me that XML file to reproduce this issue.

**Closed by dagwieers** 2017-08-24 10:49 UTC
Labels: enhancement
