### ISSUE TITLE
Allow to set attributes

### ISSUE THREAD

**Issue by alxgomz** [cmprescott/ansible-xml#104] opened 2017-04-08 23:27 UTC
It seems it is not possible at the moment the set element's attributes as the set_target function check if xpath is a node.
The goal would to set attributes like this:

```
xml:
    xmlstring: <Connector port="8080" protocol="HTTP/1.1" connectionTimeout="20000" URIEncoding="UTF-8" redirectPort="8443"/>
    xpath: /Connector/@port
    value: 8081
```

That would be very useful i think.
If I missed something jus let me know.

**Comment by berenddeschouwer** [comment] 2017-06-02 08:30
Duplicate of #15

**Comment by dagwieers** [comment] 2017-08-09 11:02
The xml module is upstream now. Please close this issue, and if needed, open a new issue at: https://github.com/ansible/ansible/issues

**Closed** 2017-08-14 22:31 UTC
