### ISSUE TITLE
Crash when attempting to `register:` XML facts

### ISSUE THREAD

**Issue by ErebusBat** [cmprescott/ansible-xml#29] opened 2015-09-08 16:24 UTC
Split from #27.

I am attempting to register some facts from a SyncThing configuration XML file.

``` yaml
- name: Config | Gather Facts
  xml:
    file: '{{st_config}}'
    xpath: /configuration
  register: st_xml
```

Will crash the playbook with:

```
TASK: [syncthing | Config | Gather Facts] *************************************
failed: [default] => {"failed": true, "parsed": false}
BECOME-SUCCESS-rvsyqlylbzmidtcwhhbagfiwfcgbtqgr
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/aburns/.ssh/config
debug1: /Users/aburns/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: /etc/ssh_config line 54: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 192.168.55.166 closed.


FATAL: all hosts have already failed -- aborting
```

Interestingly enough, if I add a `count: true` statement then it will not crash; however I am not looking for aggregate data.
## Versions

Ubuntu 14.04 LTS (fresh vagrant image)
python-lxml 3.3.3-1
python 2.7.6

**Comment by dagwieers** [comment] 2017-08-09 11:31
The xml module is upstream now (and ships with Ansible v2.4).

**Please close this issue**, and retest against the new upstream xml module. If needed, open a new issue at: https://github.com/ansible/ansible/issues

**Comment by dagwieers** [comment] 2017-08-25 13:42
I cannot reproduce this. If you can still reproduce this with the xml module from upstream (Ansible v2.4), please open a new issue at: https://github.com/ansible/ansible/issues

**Closed by dagwieers** 2017-08-25 13:42 UTC
Labels: bug
